name: increase-dev-version

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  change-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        run: |
          install.packages("usethis")
       shell: Rscript {0}

      - name: Change DESCRIPTION file
        run: |
          if(usethis:::is_dev_version()){
            desc::desc_set_version(version = usethis:::bump_version()[["dev"]])
          }
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v9
        if: ${{ success() }}
        with:
          message: 'Update dev version (Commit from Github Actions).'
          default_author: github_actions
          add: 'DESCRIPTION'
