name: increase-dev-version

on:
  workflow_call:

jobs:
  change-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ACTIONS_MANAGER_APPID }}
          private-key: ${{ secrets.ACTIONS_MANAGER_PAT }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        run: |
          install.packages("usethis")
          install.packages("git2r")
        shell: Rscript {0}

      - name: Change DESCRIPTION file and create tag
        run: |
          new_version <- usethis:::bump_version()[["dev"]]
          if(usethis:::is_dev_version()){
            desc::desc_set_version(version = new_version)
            git2r::tag(name = paste0("v", new_version))
          }
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v9
        if: ${{ success() }}
        with:
          message: '🤖 Bump development version. [skip actions]'
          default_author: github_actions
          add: 'DESCRIPTION'


