name: increase-dev-version

on:
  workflow_call:

jobs:
  change-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        run: |
          install.packages("usethis")
        shell: Rscript {0}

      - name: Change DESCRIPTION file
        run: |
          if(usethis:::is_dev_version()){
            desc::desc_set_version(version = usethis:::bump_version()[["dev"]])
          }
        shell: Rscript {0}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash



