on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


name: Main-Workflow

permissions: write-all

jobs:
  increase-version:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/increase-dev-version.yaml
    env:
      ACTIONS_MANAGER_PAT: ${{ secrets.ACTIONS_MANAGER_PAT }}
  R-CMD-Check:
    if: ${{ always() }}
    needs: [increase-version]
    uses: ./.github/workflows/R-CMD-check.yaml
  pkgdown:
    if: ${{ always() }}
    needs: [increase-version]
    uses:  ./.github/workflows/pkgdown.yaml
